### ISSUE TITLE
Cannot select downloaded song when offline and song from quick picks already selected

### ISSUE THREAD

**Issue by da-batt** [z-huang/InnerTune#1021]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Have WiFi turned off/no internet connection
2. Select song from quick picks
3. Go to downloads and select song from there

### Expected behavior

Selected song from downloads starts playing

### Actual behavior

Nothing happens

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/103059637/405f9cc5-8322-43cd-8e87-7cae8ef92e87

### InnerTune version

0.5.2

### Android version

Android 13

**Comment by Filipexos** [comment]
It also happens to me and its annoying, you have to close and open the app to change the music.

**Comment by fbck** [comment]
seems like it doesn't work offline/on unstable connections/without internet properly at all, because things just get unresponsive, songs won't play after tapping, queues get mixed up (i'd get as many as three separate playback queues at the same time lol) (and playback queues are enough of a problem on their own even with internet, as they often get mixed up).
