### ISSUE TITLE
Export data through SAF

### ISSUE THREAD

**Issue by ghost** [z-huang/InnerTune#117]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

The app should be able to export playlist data, music list data and downloaded music files. It should not require broad storage permissions and only require SAF as it does not handle external files. The music files should have the metadata intact.

Optionally, a folder could be selected to enable automatic export on certain conditions (schedule, download, etc.). Selection of a folder should only be used for this purpose. Other export functions should only require access to a file.

Ideally, the exported data should be contained within a single file. Compression is optional, but ideal. Should be in a common format (zip, tar) to allow other applications to access data.

### Why do you want this feature?

In case of the phone not having suitable backup options, or the user does not want to access the music files through the hassle of extracting the files from the backup, if possible, or the app is abandoned in the future (hopefully not too soon), the user should have access to their downloaded music files and be able to play said files through other applications. That is covered through the export function.

If the phone has no suitable app backup options available, the user should be able to transfer appropriate data to a different phone. The import/export functions covers this, though it is less useful in the case where the user is using the backup function of the phone, and can restore it on another phone.

**Comment by LokNplay** [comment]
I think this should be added cause I don't have any option to Backup/Restore on my phone and I think my playlist will be lost if I want to migrate.

**Comment by z-huang** [comment]
It will be added in the future.

**Comment by z-huang** [comment]
Open the native file manager and you'll find this.
<img width="291" alt="image" src="https://user-images.githubusercontent.com/39427017/198505271-ecb8801f-fb20-40c1-95a5-28f1b58f7497.png">

Here contains the downloaded songs, where you can open or copy to elsewhere.
<img width="292" alt="image" src="https://user-images.githubusercontent.com/39427017/198505599-bd23a5fe-6ccb-4208-9a5a-fe6bcf5bad5e.png">

It's just a preview, and I may add more content in.
Currently showing thumbnails is impossible because the app doesn't download thumbnail images but cache them by Coil. In order to support it, I have to finish other issues first.

**Comment by z-huang** [comment]
As for editing ID3 tag, since most files are webm and I couldn't find a library to edit webm tag, I won't do that right now.
I've thought of some cool uses with SAF:

1. Show the whole library to the file system, including `Artist`, `Album` and `Playlist` folders. Copying the files to other place is equivalent to downloading them and copying to the destination.
2. Add a `Online` folder. You can search inside, get results from YT Music, and copy them to other places to download.

It's cool, but I don't think I'll need them, and the feature requires the downloader to be implemented first (#13). If you really need them, say something and I'll consider.

**Comment by toruvinn** [comment]
Hello,

First of all, this app looks and works really great. Honestly, after Amazon killed Prime music (mostly), I was looking for some decent alternative and this app in beta works infinitely better than Amazon Prime music release. ;-)

I have, however, one small gripe with that thinking about the future. I was not sure what SAF was, but looks like it's basically just a way to let file explorers access data stored in app's data directory - with the app "translating" everything in between. Perhaps I understood wrong, but in the end the result seems to be the same to me: We cannot define where the data is saved.

My issue is that I always get phones with a (micro)SD card slot to expand the available storage, as the internal phone flash gets filled with a lot of stuff. What I wanted to do was to make InnerTune save the data or at least the downloaded music to my SD card, because that's where I have a lot of free space, not on the internal flash. Unfortunately, it appears this is not possible currently. SAF isn't really a solution to that, having the ability to pick an external storage folder or at least the storage (internal/SD card) like many data-heavy apps do (Amazon Prime also allowed me to download things to the SD) would be.

Would it be possible for you to reconsider adding some sort of choice here? I don't even need the data to be available to an external music player (we can already do it by exporting, although that saves the same data twice in different locations on the phone), but I would really like the ability to pick where InnerTune stores that data. I like to carry around a rather big library (think hundreds of GBs), because I listen to a lot of music.

Additionally, but this is something I am not entirely sure about, I do believe I have seen my phone allowing me to transfer some apps' data to the SD card and use it as a main storage. Potentially this might be doable with just some simple manifest switch[1], but unfortunately I don't know what else it changes. If you would enable that, that would solve my problem completely with potentially very quick and simple fix for me.

Thank you.

[1] [Android Developers -> Docs -> Guides -> manifest element -> installLocation](https://developer.android.com/guide/topics/manifest/manifest-element#install)

**Comment by selurvedu** [comment]
> As for editing ID3 tag, since most files are webm and I couldn't find a library to edit webm tag, I won't do that right now.

@z-huang

If you could make InnerTune save songs as Ogg Opus files, the problem would be solved. E.g. [Seal](https://github.com/JunkFood02/Seal) can save songs from YouTube with proper tags and album art, by relying on yt-dlp which actually does most of the job.

Here's a command for getting a tagged .opus file via yt-dlp:
```
yt-dlp --embed-metadata --embed-thumbnail -f bestaudio -x <youtube-link>
```
It is roughly equivalent to what Seal does. "Roughly" because Seal does a bit more fine-tuning (see [here](https://github.com/JunkFood02/Seal/blob/f16fbea5e76f3c84915f2d9d5fc128123aeef4de/app/src/main/java/com/junkfood/seal/util/DownloadUtil.kt#L304), and, if a corresponding option is enabled, it crops rectangular video thumbnails so that they are square and suitable for album art.

**Comment by RandomModderJDK** [comment]
Was this removed? I cannot find this feature anymore

**Comment by RandomModderJDK** [comment]
@z-huang
