### ISSUE TITLE
Replay Gain Normalization

### ISSUE THREAD

**Issue by nikhilCad** [z-huang/InnerTune#24]
In a queue, some songs are louder than others. To solve this an option of Replay Gain Normalization can be introduced in settings ( disabled by default).

**Comment by z-huang** [comment]
I'm still finding how to achieve this in ExoPlayer.

**Comment by nikhilCad** [comment]
Will this help? https://github.com/videolan/vlc/search?q=replaygain&type=

**Comment by z-huang** [comment]
I'm not sure if YouTube use ReplayGain, because some formats are webm.
However, YouTube provides "loudnessDb" and "perceptualLoudnessDb", which may be the way to implement normalized volume.

**Comment by z-huang** [comment]
I found that YouTube uses loadnessDb to convert the volume to a normalized value to make every song under a specific loadness.
![image](https://user-images.githubusercontent.com/39427017/164409259-6d1ac580-0f38-47d3-a8a1-2c83049f17d9.png)

However, NewPipe Extractor doesn't extracct "loudnessDb" and "perceptualLoudnessDb". Also, NewPipeExtractor doesn't provide the type and year of albums, and the song thumbnail is always rectangle due to fetching data from YouTube, not YouTube Music. I'll make a modified version of NewPipe Extractor to support these things.

According to my roadmap, I'll first fix the UI issues, and then getting started to remake NewPipe Extractor.

**Comment by nikhilCad** [comment]
By remaking the extractor, you wont be able to just merge the extractor
from Newpipe when Youtube breaks somethin in the site right? The "total
shutdown" days in Newpipe always happen once in while. Those will be needed
to fixed separately. So maybe you can leave it as it is? This is no that
necessary feature I think.

**Comment by z-huang** [comment]
I know that a quick hotfix is important for user experience. But I have to do that not only for the audio normalization feature, but also for more information about albums, artists and square song thumbnails. If the modification doesn't cause many conflicts with the upstream, a hotfix won't be too hard, I think. A PR may be feasible.
No matter what, I'll try to achieve that. 😊

**Comment by nikhilCad** [comment]
Relevant https://github.com/vfsfitvnm/ViMusic/commit/8a94c7e714536ef7ba6b925332b208f590ff500e
