### ISSUE TITLE
Piped Instance won't play many age restricted songs

### ISSUE THREAD

**Issue by TheTrashCrafter** [z-huang/InnerTune#791]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Find a song that isn't in Opus format and play it. (Example would be Just don't give a f--k live at Tramps by Eminem (Album: The Eminem Show)
2. You'll get an unknown error

### Expected behavior

The song should play

### Actual behavior

Unknown error

### InnerTune version

0.5.0

### Android version

Android 14 Beta 3.1

### Additional information

Device: Pixel 6A

**Comment by javdc** [comment]
The problem is not the format, that song doesn't play in the Piped instance used by Innertune to play age-restricted songs. As you can see there are both opus and m4a streams but all of them return 403 error:

https://watch.whatever.social/watch?v=PEtyXcBONds

But when using another instance (for example kavin.rocks) the streams play just fine:

https://pipedapi.kavin.rocks/streams/PEtyXcBONds

I tried changing the Piped API used in Innertune and the song plays without any errors. Maybe Innertune could have an option to change the Piped instance to solve these problems...

**Comment by TheTrashCrafter** [comment]
I changed the title now to avoid confusion.

**Comment by z-huang** [comment]
I've confirmed that the problem is the piped instance. I'll change it to `pipedapi.kavin.rocks`. Thanks for pointing out the problem. :)

**Comment by owencz1998** [comment]
@z-huang Awsome it's working perfect now thanks all 😄
