### ISSUE TITLE
Album cover rendered in low resolution

### ISSUE THREAD

**Issue by SherbetS44105** [z-huang/InnerTune#885]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. add https://music.youtube.com/watch?v=G7aJVg1iuCk to library
2. play song

### Expected behavior

album cover renders at full resolution

### Actual behavior

album cover renders at lower resolution

### Screenshots/Screen recordings

![Screenshot_20230725-224501_InnerTune](https://github.com/z-huang/InnerTune/assets/56209479/55155811-bd6f-4dbc-89ac-599cd60faf3a)

### InnerTune version

0.5.0

### Android version

Android 13

**Comment by owencz1998** [comment]
Clear cache and try listening to the song again

**Comment by z-huang** [comment]
InnerTune always uses the highest resolution thumbnail.

**Comment by Username1-a** [comment]
I think this issue should be reopened. I'm able to reproduce this bug (low-res cover images on now playing screen) on the latest stable version 0.5.3 and was able before on the previous versions. Clearing cache doesn't help.
What's more, if you go to the album view you can clearly see that the cover image there is in the higher resolution than in now playing screen.
I think you couldn't reproduce this bug before because it doesn't appear like that on every song, many cover images are fine.
![Screenshot_20231227-080214_InnerTune](https://github.com/z-huang/InnerTune/assets/47947180/f44cc8c1-8eb7-4d49-a776-ba252544e5ef)
![Screenshot_20231227-080231_InnerTune~2](https://github.com/z-huang/InnerTune/assets/47947180/d83165cd-5806-4609-84ba-82a51907e0af)

And just in case, covers that are low-res in now playing screen also appear low-res in media player in quick settings shade
![Screenshot_20231227-081215_Evolution X Launcher](https://github.com/z-huang/InnerTune/assets/47947180/13c9f006-f224-426a-ad12-32619bbe462a)
