### ISSUE TITLE
Age restricted songs won't play

### ISSUE THREAD

**Issue by corrupteddrive** [z-huang/InnerTune#980]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Click on an age restricted song.

### Expected behavior

The song should play.

### Actual behavior

It doesn't.

### Screenshots/Screen recordings

![Screenshot_2023-08-18-04-10-39-39_f4703f2d42345ac28c56f11a6100c500](https://github.com/z-huang/InnerTune/assets/78031929/e08a121e-564a-429a-a9a7-8b8dab385e6e)

### InnerTune version

0.5.1 Debug

### Android version

Android 11

**Comment by moonystars** [comment]
im having the same issue with 0.5.1 on android 11 as well. 

ive had this same issue with another app I used in the past that also pulls its music library from youtube, so im guessing its youtubes age restriction censorship and being unable to watch it unless you're on an account that can, so maybe the app can't pull the song for whatever reason because of that? unsure though, and I don't have a workaround unfortunately

**Comment by corrupteddrive** [comment]
The only workaround I have at the moment is using NewPipe

**Comment by owencz1998** [comment]
This is due to piped api is broken on some instances this is maybe a reason to have away to selected one that currently works.

**Comment by z-huang** [comment]
It would be better if the app can automatically choose a working Piped instance. However, given that only a small portion of songs are age-restricted and the implementation is annoying, I won't do it now.

**Comment by rifqire** [comment]
How about implementing [Simple YouTube Age Restriction Bypass](https://greasyfork.org/en/scripts/423851-simple-youtube-age-restriction-bypass)? Since I also have this [issue](https://github.com/z-huang/InnerTune/issues/1030). Meanwhile, if I use the userscript on Firefox for desktop and Android, age restricted songs play just fine.

![Screenshot_2023-09-04-02-01-25-351_org mozilla firefox_beta](https://github.com/z-huang/InnerTune/assets/30471081/84741d09-45bd-4a33-8124-3228de731011)
