### ISSUE TITLE
Store song cache in SD card

### ISSUE THREAD

**Issue by Mashrafidipto** [z-huang/InnerTune#987]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Hi, I'm wondering that you can make the app store the song cache in the SD card instead of the internal memory. I appreciate your work. Thanks.

### Why do you want this feature?

This would help users save space and store a large number of songs downloaded.

**Comment by KraXen72** [comment]
Hello, i would like to kindly know the reasoning behind the closing of this issue as not planned.

Also, since my other issue was closed, i would like to amend this request to not only be able store the song cache in the SD Card, but also the downloaded chunks (opaque, not openable by other media players - same way Spotify uses)

Thanks!

**Comment by kylagit** [comment]
Hello @z-huang , why is a feature to store the songs somwhere else in DRM-free form, as the user above said, not planned?
